#pragma once

#define HEIGHT_OBSERVER_ACCELEROMETER_DEVIATION         0.0084

#define HEIGHT_OBSERVER_SENSOR_BAROMETER_DEVIATION      0.4023
#define HEIGHT_OBSERVER_SENSOR_ULTRASOUND_DEVIATION     0.01
#define HEIGHT_OBSERVER_ZERO_VELOCITY_DEVIATION         0.005
