#pragma once

#define HEIGHT_OBSERVER_STATE_HEIGHT_COVARIANCE         0.1
#define HEIGHT_OBSERVER_STATE_SPEED_COVARIANCE          0.1

#define HEIGHT_OBSERVER_SENSOR_BAROMETER_COVARIANCE     0.3
#define HEIGHT_OBSERVER_SENSOR_ULTRASOUND_COVARIANCE    0.01
