#pragma once

#include <esp_err.h>

typedef esp_err_t status_t;

#define STATUS_OK                    ESP_OK
#define STATUS_FAIL                  ESP_FAIL

#define STATUS_ERR_NO_MEM            ESP_ERR_NO_MEM
#define STATUS_ERR_INVALID_ARG       ESP_ERR_INVALID_ARG
#define STATUS_ERR_INVALID_STATE     ESP_ERR_INVALID_STATE
#define STATUS_ERR_INVALID_SIZE      ESP_ERR_INVALID_SIZE
#define STATUS_ERR_NOT_FOUND         ESP_ERR_NOT_FOUND
#define STATUS_ERR_NOT_SUPPORTED     ESP_ERR_NOT_SUPPORTED
#define STATUS_ERR_TIMEOUT           ESP_ERR_TIMEOUT
#define STATUS_ERR_INVALID_RESPONSE  ESP_ERR_INVALID_RESPONSE
#define STATUS_ERR_INVALID_CRC       ESP_ERR_INVALID_CRC
#define STATUS_ERR_INVALID_VERSION   ESP_ERR_INVALID_VERSION
#define STATUS_ERR_INVALID_MAC       ESP_ERR_INVALID_MAC

#define STATUS_ERR_WIFI_BASE         ESP_ERR_WIFI_BASE
#define STATUS_ERR_MESH_BASE         ESP_ERR_MESH_BASE
